#!/usr/bin/env php
<?php

include 'vendor/autoload.php';

use Symfony\Component\Console\Application;
use Hokuken\Haik\Foundation\Application as Haik;
use Hokuken\Haik\Console\Command\ServeCommand;
use Hokuken\Haik\Console\Command\InitializeCommand;

$app = new Haik();
$console = new Application('haik', Haik::VERSION);

$console->add(new ServeCommand());
$console->add(new InitializeCommand());

$console->run();
