<?php
$config = array (
  'style_name' => 'kumo',
  'style_color' => '',
  'style_texture' => '',
  'logo_title' => 'haik',
  'logo_image' => '',
  'display_login' => 1,
  'username' => '',
  'passwd' => '',
  'smtp_server' => '',
  'smtp_auth' => 0,
  'pop_server' => '',
  'mail_userid' => '',
  'mail_passwd' => '',
  'script' => '',
  'script_ssl' => '',
  'enable_cache' => '0',
  'autolink' => 0,
  'session_save_path' => '',
  'site_close_all' => '0',
  'check_login' => 1,
  'unload_confirm' => 1,
  'http_scheme' => '',
  'encrypt_ftp' => '',
  'qhm_pw_str' => '',
  'ogp_tag' => 0,
  'add_xmlns' => '',
  'mc_api_key' => '',
  'mc_list' => array (),
  'site_title' => 'haik',
  'user_head' => '',
  'template_name' => 'top',
  'change_timestamp' => 1,
  'mail_encode' => 'ISO-2022-JP',
  'tracking_script' => '',
  'disqus_shortname' => '',
  'intro_flags' => 
  array (
    'start' => 1,
    'login' => 1,
    'admin' => 1,
    'eyecatch' => 1,
    'nav' => 1,
    'menu' => 1,
  ),
);